# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X08X4BHXSHIgmTSRJ4Njhy_VP3873p6H
"""

# Program to find symmetric difference between two sets

set1 = set(input("Enter elements of first set (space separated): ").split())
set2 = set(input("Enter elements of second set (space separated): ").split())

sym_diff = set1.symmetric_difference(set2)

print("First Set:", set1)
print("Second Set:", set2)
print("Symmetric Difference:", sym_diff)